"""Central exception hierarchy for StudentFlow."""


class StudentFlowError(Exception):
    """Base class for all StudentFlow exceptions."""


class StudentNotFoundError(StudentFlowError): ...
class AccountNotFoundError(StudentFlowError): ...
class DuplicateStudentError(StudentFlowError): ...
class StudentInWrongStateError(StudentFlowError): ...

class RepositoryNotFoundError(StudentFlowError): ...
class LocalPathNotFoundError(StudentFlowError): ...
class LocalPathNotDirectoryError(StudentFlowError): ...
class RemoteURLInvalidError(StudentFlowError): ...
class RepositoryAlreadyExistsError(StudentFlowError): ...

class CredentialNotFoundError(StudentFlowError): ...
class CredentialValidationError(StudentFlowError): ...
class SecretStorageError(StudentFlowError): ...

class GitOperationError(StudentFlowError): ...
class SyncConflictError(StudentFlowError): ...
class SyncTimeoutError(StudentFlowError): ...
class DivergedRepositoryError(StudentFlowError): ...

class HandoffError(StudentFlowError): ...
class NoActiveStudentError(HandoffError): ...
class NoNextStudentError(HandoffError): ...

class TemplateNotFoundError(StudentFlowError): ...
class TemplateCopyError(StudentFlowError): ...

class ConfigError(StudentFlowError): ...
